### ISSUE TITLE
Why worker upgrade a connection?

### ISSUE THREAD

**Issue by mohsenmoqadam** [hamidreza-s/Tecipe#4]
In Tecipe a worker wait for accepting a connection and then upgrade it, so TrasportUserOpts apply after a connection accepted.
I suggest that worker should not do upgrade connection.

**Comment by hamidreza-s** [comment]
Thanks for reporting. You are right.
It can be fixed by merging the user options with default options in `tecipe_listener_sup` file.

**Comment by hamidreza-s** [comment]
Fixed and merged as part of #7 (Implement IPv6 for Proxy-V2 Protocol) merge request.
