### ISSUE TITLE
Back to commit 'c4$'

### ISSUE THREAD

**Issue by meysam81** [hamidreza-s/Tecipe#8]
I'm starting to work in Bisphone Corp., and I've been told to use the commit that ends in c4 of this repository. Therefore I started this issue & I'll be requesting a pull that checks out to that specific commit.

**Comment by meysam81** [comment]
When you decided to merge this to development branch, please merge it to master as well. So that everyone who's going to clone the repository, gets the stable version in the master branch.
Cheers!

**Comment by hamidreza-s** [comment]
Hi, 
happy to hear that you joined the team.

Can you elaborate what issue you are solving in #9 merge request, and what do you mean by "c4"?

**Comment by meysam81** [comment]
Firstly, glad to be in the team.
And then, well, as @mohsenmoqadam mentioned in his warm-up speeches for the new crew, this repository diverted from his PATH (or so what he is calling it) and therefore we are all using the repository from the commit that has the hash ending in 'c4' hence 'c4$' (regex).
So I requested a pull so that we wouldn't have to lock the rebar to fetch the dependency from the  commit 'c4$', and so the latest commit of the master branch would be the latest stable version of the application.
I think a talk to @mohsenmoqadam would clarify it in detail. But little do I know that we are using this commit for now.

**Comment by hamidreza-s** [comment]
You can use "ref" in your `rebar.config` to get the repo as a dependency up to the commit that you want as follows:
```
{deps,[
  %% Packages
  {rebar, {git, "git://github.com/hamidreza-s/Tecipe.git", {ref, "4a9972e"}}},
  %% ...
]}.
```
`4a9972e` is the short commit hash of what you call 'c4$'.

**Comment by meysam81** [comment]
ok sure
